<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>CS 144 - Winter 2024 - Homework 4</h1></center>
<center><h1>Due: Sunday, February 11, 2024 @ 11:59pm</h1></center>

## Read *all* cells carefully and answer all parts (both text and code)

### Enter your information below:

<div style="color: #000000;background-color: #EEEEFF">
    Your Name (submitter): Rayyan Zaid  <br>
    Your student ID (submitter): 862291205
<br>
<br>
<b>By submitting this notebook, I assert that the work below is my own work, completed for this course.  Except where explicitly cited, none of the portions of this notebook are duplicated from anyone else's work or my own previous work.</b>
<br>    
<br>
<b>Instruction for submissions:</B> when you have completed this homework, download this .ipynb file to your computer by left-clicking on the file name, and submit to <a href="https://elearn.ucr.edu/">Canvas</A> by the deadline. 
<br>
<br>
<B>Late work:</B> Each student is granted five "late days" which can be used (in integer units) on any of the homework. If a more dire situation arises, please contact the instructor. DO NOT RESORT TO CHEATING.
</div>


<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>Chapter 3: Sequence Alignment</h1></center>
<br>

Chapter 3 has a <B>LOT</B> of coding challenges. In the interest of time, we will <b>skip</b> the following coding challenges on sequence alignment in the book
<UL>
<LI><A HREF="https://cogniterra.org/lesson/34012/step/10?unit=25858">Code Challenge: Find the length of a longest path in the Manhattan Tourist Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34014/step/5?unit=25860">Use OutputLCS to solve the Longest Common Subsequence Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34014/step/7?unit=25860">Solve the Longest Path in a DAG Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34017/step/3?unit=25863">Solve the Edit Distance Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34017/step/5?unit=25863">Solve the Fitting Alignment Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34017/step/7?unit=25863">Solve the Overlap Alignment Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34018/step/8?unit=25864">Solve the Alignment with Affine Gap Penalties Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34019/step/12?unit=25865">Solve the Middle Edge in Linear Space Problem (for protein strings)</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34019/step/14?unit=25865">Implement LinearSpaceAlignment to solve the Global Alignment Problem for a large dataset</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34020/step/5?unit=25866">Solve the Multiple Longest Common Subsequence Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34011/step/10?unit=25857">Solve the Change Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/34023/step/3?unit=25869">Implement Topological Ordering</A></LI>
</UL>
Those challenges above are OPTIONAL. They are good problems, but you do not need to solve it, unless you feel inclined to do so.

<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>Global Sequence Alignment</h1></center>
<br>

<div style="color: #000000;background-color: #EEFFEE">
    <font size=+2>Question 1</font><font size=+1>(15 points)</font>

Solve the <A HREF="https://cogniterra.org/lesson/34016/step/3?unit=25862">Global Alignment Problem.</A> Submit your solution to the challenge on Cogniterra and paste your Python code below.
   
Notes:
<ul>
<li>There could be multiple optimal alignments for the same input, i.e., multiple alignments with the same maximum score, but the book accepts any optimal solution</li>
<li>For tracing the alignment back, you can either reconstruct the optimal path on the dynamic programming table containing the scores, or you can produce a separate table of traceback pointers</li>
</ul>
</div>

In [1]:
!wget http://www.cs.ucr.edu/~stelo/cs144winter24/data/hw4_test1.txt

--2024-02-07 11:42:40--  http://www.cs.ucr.edu/~stelo/cs144winter24/data/hw4_test1.txt
Resolving www.cs.ucr.edu (www.cs.ucr.edu)... 169.235.30.15
Connecting to www.cs.ucr.edu (www.cs.ucr.edu)|169.235.30.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18 [text/plain]
Saving to: 'hw4_test1.txt.1'

     0K                                                       100%  492K=0s

2024-02-07 11:42:40 (492 KB/s) - 'hw4_test1.txt.1' saved [18/18]



In [2]:
## no libraries allowed except for numpy and biopython 
## no Bio.pairwise2 allowed

from Bio.Align import substitution_matrices
from numpy import zeros

def globalAlignment(x, y, sub, indel):
    """ Calculate the global alignment between sequences x and y using
        dynamic programming using the substitution matrix <sub>, and <indel> penalty
        Return the full dynamic programming table. """
    
    
    D = zeros((len(x)+1, len(y)+1), dtype=int) # initialize a numpy matrix with zeroes
 



    # No need for backtracking matrix, just check 3 incoming edges when backtracking

    # Start at the first row and populate the max score

        # f i r s t w o r d 
    #   s
    #   e 
    #   c
    #   o
    #   n
    #   d



    # Populate first row

    for j in range(1,len(y) + 1):
        previousNodeValue = D[0][j-1]


        D[0][j] = previousNodeValue + indel
    
    # Populate first column

    for i in range(1,len(x) + 1):

        previousNodeValue = D[i-1][0]
        D[i][0] = previousNodeValue + indel


    # Populate everything else besides first row and first column

    for i in range(1,len(x) + 1):

        for j in range(1,len(y) + 1):

            leftNodeValue = D[i][j-1]
            upNodeValue = D[i-1][j]
            diagonalNodeValue = D[i-1][j-1]

            leftTotalValue = leftNodeValue + indel
            upTotalValue = upNodeValue + indel

            letter1 = x[i-1]
            letter2 = y[j-1]


            # Everytime you do a diagonal move, you have to fetch it from the "sub" matrix

            diagonalEdgeValue = sub[letter1][letter2]

            diagonalTotalValue = diagonalNodeValue + diagonalEdgeValue

            D[i][j] = max(max(leftTotalValue,upTotalValue),diagonalTotalValue)


    return D




def tracebackGlobal(V, x, y, sub, indel):
    """ Trace back the alignment from position (len(x), len(y)) in global alignment matrix V """
    align1, align2 = '', ''
    
    
    
    i, j = len(x), len(y) # start from the bottom right cell
    
    # print(i,j)


    while i > 0 and j > 0:

        # Check each neighbor

        upNodeValue = V[i-1][j] + indel
        leftNodeValue = V[i][j-1] + indel

        letter1 = x[i-1]
        letter2 = y[j-1]

        diagonalNodeValue = V[i-1][j-1] + sub[letter1][letter2]

        # print(diagonalNodeValue)


            
            

        if upNodeValue >= diagonalNodeValue and upNodeValue >= leftNodeValue:

            align1 += letter1
            align2 += "-"

            i -= 1


        elif leftNodeValue >= diagonalNodeValue and leftNodeValue >= upNodeValue:
            align1 += "-"
            align2 += letter2

            j -= 1
        else:

            align1 += letter1
            align2 += letter2

            i -=1 
            j -=1

            

    while j > 0:

        letter2 = y[j-1]
        align1 += "-"
        align2 += letter2
        j-=1

    while i > 0:
        letter1 = x[i-1]
        align1 += letter1
        align2 += "-"
        i-=1



    return align1[::-1]+'\n'+align2[::-1]  # reverse the strings











f = open("hw4_test1.txt", "r")                                # open the file
blosum62 = substitution_matrices.load('BLOSUM62') # possible matrices are ['BENNER22', 'BENNER6', 'BENNER74', 'BLOSUM45', 'BLOSUM50', 'BLOSUM62', 'BLOSUM80', 'BLOSUM90', 'DAYHOFF', 'FENG', 'GENETIC', 'GONNET1992', 'HOXD70', 'JOHNSON', 'JONES', 'LEVIN', 'MCLACHLAN', 'MDM78', 'NUC.4.4', 'PAM250', 'PAM30', 'PAM70', 'RAO', 'RISLER', 'SCHNEIDER', 'STR', 'TRANS']
# blosum62 is a numpy matrix
# here is how to access the substitution cost for the aminoacid pair (A,M)
# print(blosum62.get('A').get('M'))
p1 = f.readline().strip()                                     # read the first string
p2 = f.readline().strip()                                     # read the second string

M = globalAlignment(p1, p2, blosum62, -5)                     # compute the dynamic programming matrix betwen p1 and p2, using the substitution matrix and indel penalty
# The dynamic programming matrix for this input should be
#[[  0  -5 -10 -15 -20 -25 -30]
# [ -5  -2  -6 -11 -16 -21 -26]
# [-10  -3  -5  -7 -12 -12 -17]
# [-15  -8   2  -3  -7 -12 -14]
# [-20 -13  -3   6   1  -4  -9]
# [-25 -18  -8   1   7   2  -3]
# [-30 -23 -13  -4   2   6   1]
# [-35 -28 -18  -9   2   1   4]
# [-40 -33 -23 -14  -3   1  -1]
# [-45 -38 -28 -19  -8   1   0]
# [-50 -43 -33 -24 -13  -4   8]]
# print(M)
print(M[len(p1),len(p2)])                                     # alignment score in on lower right corner cell
print(tracebackGlobal(M, p1, p2, blosum62, -5))               # print alignment

8
PLEASANTLY
-MEA--N-LY


<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>Local Sequence Alignment</h1></center>
<br>


<div style="color: #000000;background-color: #EEFFEE">
    <font size=+2>Question 2</font><font size=+1> (15 points)</font>

Solve the <A HREF="https://cogniterra.org/lesson/34016/step/10?unit=25862">Local Alignment Problem.</A> Submit your solution to the challenge on Cogniterra and paste your Python code below.

Notes:
<ul>
<li>We are providing code to access the pam250 matrix via Biopython, so that you do not have to parse the matrix from the book</li>
<li>There could be multiple optimal alignments for the same input, i.e., multiple alignments with the same maximum score, but the book accepts any optimal solution</li>
<li>For tracing the alignment back, you can either reconstruct the optimal path on the dynamic programming table containing the scores, or you can produce a separate table of traceback pointers</li>
</ul>
</div>

In [3]:
!wget http://www.cs.ucr.edu/~stelo/cs144winter24/data/hw4_test2.txt

--2024-02-07 11:42:41--  http://www.cs.ucr.edu/~stelo/cs144winter24/data/hw4_test2.txt
Resolving www.cs.ucr.edu (www.cs.ucr.edu)... 169.235.30.15
Connecting to www.cs.ucr.edu (www.cs.ucr.edu)|169.235.30.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15 [text/plain]
Saving to: 'hw4_test2.txt'

     0K                                                       100%  379K=0s

2024-02-07 11:42:41 (379 KB/s) - 'hw4_test2.txt' saved [15/15]



In [4]:
## no libraries allowed except for numpy, itertools and biopython
## no Bio.pairwise2 allowed

from numpy import zeros, where, unravel_index, argmax, shape
from Bio.Align import substitution_matrices

def localAlignment(x, y, sub, indel):
    ''' Calculate local alignment values of sequences x and y using
        dynamic programming.  Returns the dynamic programming table and
        the matrix of traceback pointer (0,1,2,3) where 0: stop, 1: diagonal, 2: up, 3: left '''
    D = zeros((len(x)+1, len(y)+1), dtype=int) # numpy matrix for scores
    T = zeros((len(x)+1, len(y)+1), dtype=int) # numpy matrix for pointers (0: stop, 1: diagonal, 2: up, 3: left)
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    return D,T

def tracebackLocal(T, x, y, i, j):
    """ Trace back the alignment from position (i,j) in
        matrix T of traceback pointers for strings x and y.
        Returns an alignment string """
    align1, align2 = '', ''
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    return align1[::-1]+'\n'+align2[::-1] # reverse the strings

f = open("hw4_test2.txt", "r")                                # open the file
p1 = f.readline().strip()                                     # read the first string
p2 = f.readline().strip()                                     # read the second string

pam250 = substitution_matrices.load('PAM250') # possible matrices are ['BENNER22', 'BENNER6', 'BENNER74', 'BLOSUM45', 'BLOSUM50', 'BLOSUM62', 'BLOSUM80', 'BLOSUM90', 'DAYHOFF', 'FENG', 'GENETIC', 'GONNET1992', 'HOXD70', 'JOHNSON', 'JONES', 'LEVIN', 'MCLACHLAN', 'MDM78', 'NUC.4.4', 'PAM250', 'PAM30', 'PAM70', 'RAO', 'RISLER', 'SCHNEIDER', 'STR', 'TRANS']
# pam250 is a numpy matrix
# here is how to access the substitution cost for aminoacid pair (A,M)
# print(pam250.get('A').get('M'))

M,T = localAlignment(p1, p2, pam250, -5)      # compute the dynamic programming matrix and traceback pointers, -5 is the penalty for indel
(i,j) = unravel_index(argmax(M), M.shape)     # index of the max in the matrix using numpy
# The dynamic programming matrix for this input should be
#[[ 0  0  0  0  0  0  0  0]
# [ 0  0  0  0  0  4  0  0]
# [ 0  0  4  1  0  0  4  0]
# [ 0  1  0  4  3  0  1  1]
# [ 0  0  2  2  4  0  0  0]
# [ 0  0  0  0  0 10  5  0]
# [ 0  0  0  0  0  5  7 15]]
print(M.max())                                # alignment score is the max in the matrix
print(tracebackLocal(T, p1, p2, i, j))        # print alignment

0


